langauge: python
python:
  - 3.5

services:
  - docker

install:
  - docker build --tag eyadsibai/docker-dsp:latest-python . -f Dockerfile.python
  - docker build --tag eyadsibai/docker-dsp:latest-torch . -f Dockerfile.torch
  - docker build --tag eyadsibai/docker-dsp:latest . -f Dockerfile
