name: root
dependencies:
  - python=3.5
  - lxml=3.6.0
  - jupyterlab
  - bokeh=0.12.*
  - cloudpickle=0.2.*
  - dask=0.13.*
  - distributed
  - h5py=2.6.*
  - hdf5=1.8.*
  - ipywidgets=5.2*
  - luigi=2.*
  - matplotlib
  - mccabe
  - networkx=1.11.*
  - nltk=3.2.*
  - numba
  - numexpr=2.6.*
  - numpy
  - requests=2.10.*
  - seaborn
  - pandas=0.19.*
  - bottleneck
  - scikit-learn=0.18.1
  - scikit-image=0.12.*
  - scipy=0.18.*
  - nltk
  - statsmodels=0.6.*
  - patsy=0.4.*
  - cython
  - bcolz
  - psutil # needed for pydatalab
  - pysal
  - datashader
  - conda-forge::pymc3
  - conda-forge::pudb
  - glemaitre::imbalanced-learn
  - conda-forge::altair
  - tpot
  - prettytable
  - joblib>=0.10.3
  - geojson=1.3.3
  - ggplot
  - Pillow
  - Proj4
  - cytoolz
  - toolz
  - plotly
  - haversine
  - mpld3
  - mplleaflet
  - arrow
  - deap
  - gpxpy
  - python-igraph
  - line_profiler
  - pandas-profiling
  - matplotlib-venn
  - pystan
  - ImageHash
  - tifffile
  - descartes
  - cartopy
  - shapely
  - cvxopt
  - opencv
  - snowballstemmer
  - babel
  - hdbscan
  - spacy
  - sklearn-contrib-lightning
  - forestci
  - pyshp
  - pyproj
  - basemap
  - pip=9.0.1
  - category_encoders
  - lifelines
  - google-api-python-client
  - tensorflow=0.12.1
  - keras
  - gensim
  - geopy
  - jellyfish
  - imagesize=0.7.1
  - pytools
  - pyparsing
  - setuptools=32.3.1
  - python-dotenv
  - soumith::pytorch
  - soumith::torchvision
  # - theano
 # - Quantopian::zipline
