name: root
dependencies:
  - python=3.5
  - lxml=3.6.0
  - jupyterlab
  - bokeh=0.12.*
  - cloudpickle=0.2.*
  - dask=0.13.*
  - h5py=2.6.*
  - hdf5=1.8.*
  - ipywidgets=5.2*
  - luigi=2.*
  - matplotlib=1.5.*
  - mccabe
  - networkx=1.11.*
  - nltk=3.2.*
  - numba
  - numexpr=2.6.*
  - numpy=1.11.*
  - requests=2.10.*
  - seaborn
  - pandas=0.19.*
  - bottleneck
  - scikit-learn=0.18.1
  - scikit-image=0.12.*
  - scipy=0.18.*
  - nltk
  - statsmodels=0.6.*
  - patsy=0.4.*
  - cython
  - bcolz
  - psutil # needed for pydatalab
  - pysal
  - datashader
  - conda-forge::pymc3
  - conda-forge::pudb
  - glemaitre::imbalanced-learn
  - conda-forge::altair
  - tpot
  - prettytable
  - joblib>=0.10.3
  - geojson=1.3.3
  - ggplot
  - Pillow
  - Proj4
  - cytoolz
  - toolz
  - plotly
  - haversine
  - mpld3
  - mplleaflet
  - arrow
  - deap
  - gpxpy
  - python-igraph
  - line_profiler
  - pandas-profiling
  - matplotlib-venn
  - pystan
  - ImageHash
  - tifffile
  - descartes
  - cartopy
  - shapely
  - cvxopt
  - opencv
  - snowballstemmer
  - babel
  - hdbscan
  - spacy
  - sklearn-contrib-lightning
  - forestci
  - pyshp
  - pyproj
  - basemap
  - pip=9.0.1
  - category_encoders
  - lifelines
  - google-api-python-client
  - tensorflow=0.12.1
  - keras
  - gensim
  - geopy
  - jellyfish
  - imagesize=0.7.1
  - pytools
  - pyparsing
  - setuptools=32.3.1
  # - theano
 # - Quantopian::zipline
  - pip:
      - google-cloud
#      - https://storage.googleapis.com/cloud-ml/sdk/cloudml.latest.tar.gz
      - git+https://github.com/marcotcr/lime.git
      - lifetimes
      - geopandas
      - tsfresh
      - futures>=3.0.5
      - seasonal
      - visualize_ML
      # - edward
      - git+https://github.com/AmazaspShumik/sklearn_bayes.git
      - sigopt_sklearn[ensemble]
      - tdigest
      - git+https://github.com/fukatani/rgf_python.git
      - git+https://github.com/hyperopt/hyperopt-sklearn.git
      - sklearn-pandas
      - datacleaner
      - bambi
      - git+https://github.com/ferrine/gelato.git
   #   - auto-sklearn
      - git+https://github.com/Lasagne/Lasagne.git
#      - tensorflow-gpu
      # - scikit-cuda==0.5.1
      - datatest
      - jieba
      - cvxpy
      # - pycuda
   #   - rep --no-dependencies
      - categorical-distance>=1.9
      - quiver_engine
      - db.py
      - dedupe
      - dedupe-hcluster
      - parserator>=0.6.2
      - probableparsing>=0.0.1
      - probablepeople>=0.5.2
      - git+git://github.com/rasbt/mlxtend.git#egg=mlxtend
      - pyalgotrade
      - git+https://github.com/hammerlab/fancyimpute.git
      - husl
      - ml_metrics
      - pyflux
      - mne
      - pyshp
      - pytagcloud
      - textblob
      - git+https://github.com/amueller/word_cloud.git
      - chainer
      - records
      - xgboost
      - sexmachine
      - Geohash
      - sacred
      - git+https://github.com/nicta/dora.git
      - git+https://github.com/hyperopt/hyperopt.git
      - tflearn
      - fitter
      - vowpalwabbit
      - langid
      - delorean
      - trueskill
      - heamy
      - git+https://github.com/nicolashennetier/pyeconometrics.git
      - vida
      - missingno
      - s2sphere
      - bayesian-optimization
      - git+https://github.com/ztane/python-Levenshtein.git
      - pyldavis
      - orderedmultidict
      - smhasher
      - nolearn
      - keras-vis
      - git+https://github.com/danielhomola/boruta_py.git
      - git+https://github.com/NervanaSystems/neon.git
      - pybrain
      - stop-words
      - hep_ml
      - git+https://github.com/matthiasplappert/keras-rl.git
      - git+https://github.com/vitruvianscience/opendeep.git
      - git+https://github.com/lyst/lightfm.git
      - git+https://github.com/scikit-learn-contrib/py-earth.git
      - git+https://github.com/scikit-learn-contrib/polylearn.git
      - git+https://github.com/DistrictDataLabs/yellowbrick.git@develop
