name: root
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.5
  - bokeh=0.12.*
  - cloudpickle=0.2.*
  - dask=0.13.*
  - h5py=2.6.*
  - hdf5=1.8.*
  - ipywidgets=5.2*
  - luigi=2.*
  - matplotlib=1.5.*
  - mccabe=0.3.*
  - networkx=1.11.*
  - nltk=3.2.*
  - numba=0.29.*
  - numexpr=2.6.*
  - numpy=1.11.*
  - requests=2.10.*
  - seaborn=0.7.*
  - pandas=0.19.*
  - scikit-learn=0.18.*
  - scikit-image=0.12.*
  - scipy=0.18.*
  - nltk
  - statsmodels=0.6.*
  - patsy=0.4.*
  - cython
  - bcolz
  - psutil # needed for pydatalab
  - pysal
  - datashader
  - conda-forge::pymc3
  - conda-forge::pudb
  - glemaitre::imbalanced-learn
  # - conda-forge::altair
  - tpot
  - prettytable
  - joblib=0.10.3
  - geojson=1.3.3
  - seaborn
  - ggplot
  - Pillow
 # - Quantopian::zipline
  - pip:
  #    - google-cloud
#      - https://storage.googleapis.com/cloud-ml/sdk/cloudml.latest.tar.gz
      - keras
      - tensorflow-gpu
      - categorical-distance==1.9
      - db.py
      - dedupe
      - dedupe-hcluster
      - google-api-python-client==1.5.1
      - haversine==0.4.5
      - parserator==0.6.2
      - probableparsing==0.0.1
      - probablepeople==0.5.2
      - git+git://github.com/rasbt/mlxtend.git#egg=mlxtend
      - pyalgotrade
      - haversine
      - git+https://github.com/hammerlab/fancyimpute.git
      - husl
      - geopy
      - ml_metrics
      - mne
      - pyshp
      - gensim
      - pytagcloud
      - textblob
      - git+git://github.com/amueller/word_cloud.git
      - python-igraph
      - chainer
      - mpld3
      - mplleaflet
      - gpxpy
      - arrow
      - sexmachine
      - Geohash
      - deap
      - toolz
      - cytoolz
      - sacred
      - plotly
      - git+https://github.com/nicta/dora.git
      - git+https://github.com/hyperopt/hyperopt.git
      - git+https://github.com/tflearn/tflearn.git
      - fitter
      - langid
      - delorean
      - trueskill
      - heamy
      - vida
      - missingno
      - pandas-profiling
      - s2sphere
      - git+https://github.com/fmfn/BayesianOptimization.git
      - git+https://github.com/ztane/python-Levenshtein.git
      - matplotlib-venn
      - pyldavis
      - pystan
      - ImageHash
      - tifffile
      - descartes
      - line_profiler
      - orderedmultidict
      - smhasher
      - git+https://github.com/SciTools/cartopy.git
      - nolearn
      - git+https://github.com/danielhomola/boruta_py.git
      - git+https://github.com/NervanaSystems/neon.git
      - shapely[vectorized]==1.6b2
      - pybrain
      - git+https://github.com/arogozhnikov/hep_ml.git
      - git+https://github.com/matthiasplappert/keras-rl.git
      - git+https://github.com/danielfrg/tsne
      - git+https://github.com/vitruvianscience/opendeep.git


      #- git+https://github.com/blaze/dask.git#egg=dask[complete]

