name: root
dependencies:
  - python=3.6
  - pandas>=0.2.1
  - boto
  - boto3
  - lxml>=3.6.0
  - jupyterlab
  - bokeh>=0.12.*
  - cloudpickle>=0.2.*
  - dask>=0.13.*
  - distributed
  - h5py>=2.6.*
  - hdf5>=1.8.*
  - ipywidgets>=5.2*
  - luigi>=2.*
  - matplotlib>=2.*
  - mccabe
  - networkx>=1.11.*
  - nltk=3.2.*
  - numba
  - numexpr>=2.6.*
  - numpy
  - requests>=2.*
  - seaborn
  - orange3
  - orange3-text
  - holoviews
  - bottleneck
  - scikit-learn>=0.18.1
  - scikit-image>=0.12.*
  - scipy>=0.19.*
  - nltk
  - statsmodels>=0.6.*
  - patsy>=0.4.*
  - cython
  - bcolz
  - psutil # needed for pydatalab
  - pysal
  - datashader
  - conda-forge::pymc3
  - glemaitre::imbalanced-learn
  - conda-forge::altair
  - blaze
  - prettytable
  - gdal
  - SimpleITK::SimpleITK
  - ggplot
  - Pillow
  - Proj4
  - cytoolz
  - toolz
  - plotly
  - haversine
  - textacy
  - mpld3
  - mplleaflet
  - arrow
  - graphviz
  - gpxpy
  - python-igraph
  - line_profiler
  - george
  - pandas-profiling
  - matplotlib-venn
  - pystan
  - ImageHash
  - tifffile
  - descartes
  - biopython
    # - shogun
  - cartopy>=0.14.2
  - shapely>=1.5.*
  - cvxopt
  - opencv
  - snowballstemmer
  - babel
  - hdbscan
  - spacy
  - rpy2
  - sklearn-contrib-lightning
#  - forestci
  - pyshp
  - geoplot
  - pyproj
  - bqplot
  - basemap
  - pip>=9.0.1
  - google-api-python-client
  - geopy
  - gensim
#  - jellyfish
  - imagesize>=0.7.1
  - pytools
  - pyparsing
  - plotnine
  - setuptools>=32.3.1
  - python-dotenv
  - soumith::pytorch
  - soumith::torchvision
  - fiona
  - poliastro
 # - pymc::hddm
  # -  microscopes-common
  # - microscopes-{mixturemodel, irm, lda}
  - theano
  # - Quantopian::zipline
