name: root
dependencies:
  - python=3.6
  - pandas>=0.2.1
  - boto
  - boto3
  - lxml>=3.6.0
  - jupyterlab
  - bokeh>=0.12.*
  - cloudpickle>=0.2.*
  - dask>=0.13.*
  - distributed
  - h5py>=2.6.*
  - hdf5>=1.8.*
  - ipywidgets>=5.2*
  - luigi>=2.*
  - matplotlib>=2.*
  - mccabe
  - networkx>=1.11.*
  - nltk=3.2.*
  - numba
  - numexpr>=2.6.*
  - numpy
  - requests>=2.*
  - seaborn
  - holoviews
  - bottleneck
  - scikit-learn>=0.18.1
  - scikit-image>=0.12.*
  - scipy>=0.19.*
  - nltk
  - statsmodels>=0.6.*
  - patsy>=0.4.*
  - cython
  - bcolz
  - psutil # needed for pydatalab
  - pysal
  - datashader
  - conda-forge::pymc3
  - glemaitre::imbalanced-learn
  - conda-forge::altair
  - blaze
  - prettytable
  - gdal
  - SimpleITK::SimpleITK
  - ggplot
  - Pillow
  - Proj4
  - cytoolz
  - toolz
  - plotly
  - haversine
  - mpld3
  - mplleaflet
  - arrow
  - graphviz
  - gpxpy
  - python-igraph
  - line_profiler
  - pandas-profiling
  - matplotlib-venn
  - pystan
  - ImageHash
  - tifffile
  - descartes
  - cartopy>=0.14.2
  - shapely>=1.5.*
  - cvxopt
  - opencv
  - snowballstemmer
  - babel
  - hdbscan
  - spacy
  - sklearn-contrib-lightning
#  - forestci
  - pyshp
  - geoplot
  - pyproj
  - bqplot
  - basemap
  - pip>=9.0.1
  - google-api-python-client
  - geopy
  - gensim
#  - jellyfish
  - imagesize>=0.7.1
  - pytools
  - pyparsing
  - plotnine
  - setuptools>=32.3.1
  - python-dotenv
  - soumith::pytorch
  - soumith::torchvision
  - fiona
  # - r::r-essentials
  # - r::r-devtools
  # -  microscopes-common
  # - microscopes-{mixturemodel, irm, lda}
  - theano
  # - Quantopian::zipline
  - pip:
    - git+git://github.com/scikit-learn-contrib/forest-confidence-interval.git #forestci
    - deap
    - tpot
    - joblib
    - nxviz
    - scikit-dsp-comm[helpers]
    - perfplot
    # - copper
    - tdda
    - pystruct
    - airflow
    - nbdime
    - geojson
    - category_encoders
    - spectral
    - lifelines
    - lsanomaly
    - skll
    - speedml
    - mlens
    - pomegranate
    - google-cloud
   # - dm_sonnet
    - bhtsne
    - tslearn
    - tqdm
    - tensorboard-pytorch
    - mpl-scatter-density
    - sympy
    - kapre
    - squarify
    - py_stringsimjoin
    - lifetimes
    - fuzzywuzzy
    - python-louvain
    - pyexcel-ods
    - geopandas
    - tsfresh
    - xcessiv
    - hypertools
    - futures>=3.0.5
    - seasonal
    - few
    - Skater
    - scikit-garden
    - lightgbm
    - mxnet
    - tensorflow>=1.0.1
    - scikit-plot
    - visualize_ML
    - workalendar
    - sigopt_sklearn[ensemble]
    - tdigest
    - sklearn-pandas
    - datacleaner
    - bambi
    - datatest
    - jieba
    - cvxpy
    - qgrid
    - categorical-distance>=1.9
    - quiver_engine
    - db.py
    - dedupe
    - dedupe-hcluster
    - parserator>=0.6.2
    - probableparsing>=0.0.1
    - probablepeople>=0.5.2
    - pyalgotrade
    - husl
    - ml_metrics
    - pyflux
    - mne
    - pyshp
    - fbprophet
    - metric-learn
    - pytagcloud
    - textblob
    - chainer
    - records
    - xgboost
    - sexmachine
    - Geohash
    - sacred
    - tflearn
    - fitter
    - vowpalwabbit
    - langid
    - delorean
    - trueskill
    - heamy
    - vida
    - missingno
    - s2sphere
    - bayesian-optimization
    - pyldavis
    - lmfit
    - orderedmultidict
    - smhasher
    - nolearn
    - pynlpl
    - keras-vis
    - pybrain
    - stop-words
    - hep_ml
    - kaggle-cli
    - tfdebugger
    - fasttext
    - hmmlearn
    - wavio
    - terminalplot
    - jupyterthemes
    - mlxtend
    - keras-rl
    - h5py
    - scikit-optimize
    - bayespy
    - gplearn
    - keras
    - lime
    - fancyimpute
    - lightfm
    - lightgbm
    - hyperopt
    - boruta
    - yellowbrick
    - nilearn
    - featureforge
    - Dora
    - dflearn
    # - bilearn
    - vecstack
    - astroML
    - fastFM
    - tensorlayer
    - pdpipe
    - keras-vis
    - linearmodels
    - edward
    - leven
    - rgf_python
    - catboost
    - mlbox
    - gmaps
    - paramnb
    - folium
    - auto_ml
    - git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans
    - git+https://github.com/reinforceio/tensorforce.git
    - git+https://github.com/AmazaspShumik/sklearn_bayes.git
    - git+https://github.com/ferrine/gelato.git
    - git+https://github.com/Lasagne/Lasagne.git
    - git+https://github.com/hyperopt/hyperopt-sklearn.git
    - git+https://github.com/amueller/word_cloud.git
    - git+https://github.com/nicta/dora.git
    - git+https://github.com/nicolashennetier/pyeconometrics.git
    - git+https://github.com/ztane/python-Levenshtein.git
    - git+https://github.com/NervanaSystems/neon.git@v1.9.0
    - git+https://github.com/vitruvianscience/opendeep.git
    - git+https://github.com/scikit-learn-contrib/py-earth.git
    - git+https://github.com/scikit-learn-contrib/polylearn.git
    - git+https://github.com/ioam/geoviews.git
    - git+https://github.com/erp12/pyshgp.git
    #  - git+https://github.com/jupyter/jupyter-drive.git
    # scikit-cuda==0.5.1
    # auto-sklearn
    # pycuda
