- cffi
- chainer_sklearn
- deap

- ezyang::onnx
- git+git://github.com/ppwwyyxx/tensorpack
# - git+https://github.com/Lasagne/Lasagne.git
# - git+https://github.com/alshedivat/keras-gp
# - git+https://github.com/casperkaae/parmesan.git
# - git+https://github.com/ferrine/gelato.git
# - git+https://github.com/tariqdaouda/Mariana.git


- git+https://github.com/facebookresearch/DrQA.git
- git+https://github.com/facebookresearch/pysparnn.git
- git+https://github.com/tensorflow/cleverhans.git#egg=cleverhans
- git+https://github.com/thtrieu/darkflow.git
- git+https://github.com/thu-ml/zhusuan     # Bayesian Deep Learning, Generative Models, Based on Tensorflow
- gym

- nutsml     # Flow-based data pre-processing for deep learning
- picasso-viz # (should be in dockerfile by itself)
- theano
