name: root
channels:
  - conda-forge
  - glemaitre
  - maciejkula
  - ioam
  - defaults
  - pkgw-forge
  - datamicroscopes
  - distributions

dependencies:
  - python=3.6
  - pip>=9.0
#  - jupyterlab
  - tim_shawver::qgrid
  - ipywidgets
  - paramnb
#  - bleach>=2.1.2 #latest version needed by beakerx
#  - beakerx
  - nodejs
  - openjdk
  - maven
  - libgcc
  - gdal>=2.1 # required by yatsm
  - hunspell

  # Cloud Services
  - boto
  - boto3
  - google-cloud-core
  - s3fs

  # python toolings
  - cytoolz
  - toolz
  - pytools
  - python-dotenv
  - fire
  - tqdm

  # formatting
  - mccabe
  - flake8
  - yapf

  # Stats and math
  - sympy
  - scipy>=0.19.*
  - patsy>=0.4.*
  - statsmodels>=0.6.*
  - haversine
  - emcee
  #- kcbo # ver old... someone should update it
  # - sixpack # ab testing

  # profiling code
  - line_profiler
  - memory_profiler


  # Data Exploration
  - jos_pol::pandas-profiling
  - missingno     # Missing data visualization module
  - scikit-data



  # Data Analysis Tools
  - pandas>=0.22.0
  - vaex
  - fastparquet
  - cloudpickle>=0.2.*
  - dask>=0.15.*
  - dask-ml
  - dask-xgboost
  - distributed
  - h5py>=2.7.*
  - hdf5>=1.8.*
  - numba
  - numexpr>=2.6.*
  - numpy
  - bcolz
  - hyperspy  # multi-dimensional data analysis
  - arrow
  - xarray
  - scikit-sparse # sparse data lib



  # Visualization
  - bokeh>=0.12.*
  - matplotlib>=2.*
  - mpl-probscale
  - ggplot
  - plotly
  - matplotlib-venn     # Area-weighted venn-diagrams for Python/matplotlib
  - plotnine # grammar of graphics
  - seaborn # statistical data visualization
  - bokeh::datashader   # visualize big datasets
  - conda-forge::altair
  - mpld3   # D3 Renderings of Matplotlib Graphics
  - ioam::holoviews
  - districtdatalabs::yellowbrick     # Visual analysis and diagnostic tools to facilitate machine learning model selection

  - bokeh::colorcet # colormaps
  - mplleaflet
  #- glueviz::glueviz
  - folium
  - mpl-scatter-density
  - bqplot
  - descartes # visualize geopositions
  - amueller::wordcloud
  - ipyleaflet
  - windrose


  # General Purpose ML
  - orange3
  - python-annoy   # Approximate Nearest Neighbors
  - scikit-learn>=0.18.1
  - glemaitre::imbalanced-learn
  - hdbscan
  - h2oai::h2o
  - xgboost
  - sklearn-contrib-lightning   # Large-scale linear classification, regression and ranking i
  - nearpy     # approximated nearest neighbour
  - lightgbm
  - lmfit


  # specific problem ml libs
  - lifelines # Survival analysis
  - spotlight
  - george
#  - y_ohr_n::kenchi
# - face_recognition
  #- nupic


  # databases read
  - records

  # Bayesian
  - conda-forge::pymc3
  - pomegranate #probabilistic modelling
  - pystan


  # preprocessing & feature engineering
  - category_encoders
  - csvkit
  - ftfy
# - sklearn-deap2
# - sklearn-deap

# geo spatial data
  #- fiona
  #- pyshp
  #- rpforest # random projections forest
    # - geopandas
 # - geoplotlib
  # - geoplot   # geospatial data visualization
#   - shapely>=1.5.*
#   - cartopy>=0.14.2
#   - basemap
#  - geoviews
#   - gmaps
  # - gpxpy   # gps format parser
  # - geojson
  # - pysal # spatial data analysis

  # Testing
  - pytest
  - cerberus     # data validation functionality
  - validictory
  - engarde
  - hypothesis


  # Network Analysis
  - networkx>=2.*
  - graphviz
  - python-igraph
  - nxviz
  - ostrokach-forge::graph-tool


# Time Series
  - tsfresh   # Automatic extraction of relevant features from time series
  - fbprophet
# automl
  - tpot


# Models Interpretation and management and meta learning
  - Skater # Model Agnostic Interpretation
  - eli5 # inspecting machine learning classifiers and explaining their predictions
  - scikit-plot     # add plotting functionality to scikit-learn objects.
  - mlxtend  # extension and helper modules for Python's data analysis and machine learning libraries.
  - lime
  - pandas_ml     # pandas, scikit-learn, xgboost and seaborn integration
  - scikit-optimize
  # rep --no-dependencies
    # - modeldb
  # - sacred
  # - skll # easy to run machine learning experiments (scikit-learn)
    # - xcessiv

  # External Data
  - geopy


  # workflow managements & parallelization
#  - airflow
  - luigi
#  - horovod
  - joblib
  - dask-searchcv

# algorithms
  - uwmagellan::py_stringsimjoin


  # OR packages
  - pyomo
  - pyomo.extras
  - salib
  - cvxopt
  - pulp


  # suport others
  #- lesscpy # may be needed by some tool
  - cython
  - swig
  - mistune
  - tabulate
  - requests>=2.*
  - paramz
  - lxml>=3.6.0
  - pyyaml
  - funcy
  - cmd2
  - bottleneck # faster pandas
  - rpy2 # interface to R from python
  # - knowledge-repo #(should be in a dockerfile by itself)

# NLP
  - nltk
  - gensim
  - spacy
  - fasttext

#  - nickledave::hybrid-vocal-classifier # vocalization

# Natural Language Processing
#   - orange3-text
# - chatterbot
# - affinegap


# Image Processing
  - SimpleITK::SimpleITK
  - imagemagick
  - imagesize>=0.7.1 # parses image files’ header and return image size.
  - ImageHash   # image hashing library
  - scikit-image>=0.12.*
  - opencv
  - Pillow
#  - pdftabextract
  - tifffile
# - vtk

# Neuroscience & Medical & molecular Biology
#   - dipy
#   - nibabel #neuroimaging file format
#   - pydicom # read/ write dicom files
#  - nilearn
# - biopython
  # - mne # human neurophysiological data
#  - git+https://github.com/analysiscenter/cardio.git ml for cardio data

# Astronomy
#   - PyAstronomy
#   - astroML
#   - sunpy solar physics

# Audio & music
#   - librosa
# - python_speech_features
# - git+https://github.com/keunwoochoi/kapre.git # Keras Audio Preprocessors
# - magenta
# pydub


# Geometry
#   - s2sphere

# deep learning
  - tensorflow>=1.4.0
  - pytorch::pytorch
  - pytorch::torchvision
  - keras
  - chainer
  - demetris::pydlt
#  - nusdbsystem::singa



  - r::r-essentials
  - r::r-devtools
  - r::r-base
  - r::r-irkernel
  - r::r-plyr
  - r::r-shiny
  - r::r-tidyverse
  - r::r-markdown
  - r::r-forecast
  - r::r-reshape2
  - r::r-randomforest
  - r::r::r-caret
  - r::r-ggplot2
  - rpy2
  - r::r-rsqlite
  - r::r-caret
  - r::r-rcurl
  - r::r-tseries
  - r::r-survival
  - r::r-rstan
  - r::r-rocr
  - r::r-lme4
  - r::r-kernsmooth
  - r::r-glmnet
  - r::r-ggplot2
  - r::r-modelmetrics
  - r::r-e1071
  - r::r-anomalydetection
  - r::r-rcpp
  - r::r-crayon

  - pip:
# python-toolings
    - disp
    - kaggle-cli
    - kaggle
    - kaggler
    - mmh3
    - recipy
    - better_exceptions # better exceptions
    # data manipulation
    - xmltodict
    - tablib[pandas]
    - psutil
    - marisa-trie
    - more-itertools

# social networks data
    - tweepy

# command_lines
    - s3cmd

# data processing
    - git+https://github.com/SohierDane/BigQuery_Helper#egg=bq_helper

# stats and math
    - bootstrapped
    - fitter
    - ml_metrics
    - bayesian_bootstrap
    - bayesian-optimization
    - causalinference
#    - causality needs pymc ... should be switched to pymc3
    - cma
    - pgmpy
    - elfi
    - expan
    - pymc3_models
    - git+https://github.com/manuel-calzolari/sklearn-genetic.git # genetic algorithms
    - pyemd #  Earth Mover's Distance

# data exploration
    - optimuspyspark     # cleaning and much more, pre-processing and exploratory data analysis in a distributed fashion with Apache Spark
    - spark-df-profiling
    - pandas-summary
    - edaplotting
    - edatools

# data analysis tools
#    - meza     # processing tabular data (I think this is useless)
    - datacleaner     #  automatically cleans data sets and readies them for analysis.
    - Geohash
    - prices
    - tdigest # data structure for large data analysis
    - urlextract
    - messytables
    - barely_json
    - rows #tabular data with wierd formats
    - pyexcel-ods    # ods formats
    - pythonflow
    - moviepy


# profiling & debugging code
    - py-heat
    - pudb

# visualizations & plots
    - kmapper
    - umap-learn
    - hypertools
    - matplotlib_venn_wordcloud
    - pyldavis
    - jmpy
    - cufflinks
    - pyhsmm
    - bhtsne # is it better than scikit-learn ... should be tested
    - pdvega
    - pyupset
    - bowtie # dashboard
    - pyecharts
#     - visdom python server for pytorch visualization should be in a different docker image
#    - vapeplot # matplotlib extension for vaporwave aesthetics

# general ML
    - scikit-garden  # A garden for scikit-learn compatible trees
    - scikit-multilearn
    - git+https://github.com/larsmans/seqlearn.git     # Sequence learning toolkit
    - forestci
    - git+https://github.com/arogozhnikov/infiniteboost.git     # building infinite ensembles with gradient descent
    - skope-rules
    - sklearn_contrib_py_earth
    - pystruct # structured learning
    - kmodes     # k-modes and k-prototypes clustering algorithms
    - vowpalwabbit # could not find boost library
    - catboost
    - sklearn-compiledtrees
    - lightfm
    - guidedlda
    - minisom
    - hdidx
    - linearmodels
    - rgf_python # just an interface ... should install the tool too
    - fastFM
    - sklearn-glvq
    - markovify
    - xlearn
    - glmnet_py
    - sf-diamond
    - git+https://github.com/eriklindernoren/NapkinML
    - http://s3.amazonaws.com/h2o-deepwater/public/nightly/latest/h2o-3.13.0-py2.py3-none-any.whl
    # - sklearn-extensions old version supporting only old libs

# Specific ML
    - lifetimes # Lifetime value
    - git+https://github.com/nicolashennetier/pyeconometrics.git # econometrics regression models
    - quantecon # quantitative economics
#    - git+https://github.com/tmadl/semisup-learn --no-deps # it installs wrong sklearn
    - git+https://github.com/timvieira/crf.git
    - pystruct
    - sklearn-crfsuite
    - parserator>=0.6.2
    - dedupe
    - dedupe-hcluster
    - gplearn
    - metric-learn
    - git+https://github.com/garydoranjr/misvm.git#egg=misvm
    - implicit # Collaborative Filtering for Implicit Datasets.
    - hep_ml
    - pygam # Generalized Additive Models in Python
    - git+https://github.com/albertcthomas/anomaly_tuning
    - libact # active learning needs liblapacke-dev
    - modAL # active learning
    - scikit-survival
    - causalimpact
    - costcla
    - causal-impact
    - luminol
    - zoopt
    - kenchi
    - Dora
    - edapy
    - gpy # gaussian processes



# recommendation systems
    - git+https://github.com/marinkaz/nimfa
    - git+https://github.com/chyikwei/recommend
    - recsys
    - git+https://github.com/Evfro/polara
    - flurs
    - cmfrec

# Bayesian
    - bambi     # BAyesian Model-Building Interface
    - git+https://github.com/AmazaspShumik/sklearn_bayes.git
    - git+https://github.com/scikit-learn-contrib/polylearn.git
#    - git+https://github.com/nicta/dora.git # Nonparametric Active Sampling
    - edward
    - hmmlearn # Hidden Markov Models
    - MarkovNetwork
    - scikit-surprise
    - lsanomaly # probabilistic anomaly detector
    - bayespy

# Preprocessing and feature engineering
    - path.py # processing paths and files
    - fancyimpute     # impute missing data
    - git+https://github.com/jundongl/scikit-feature
    - git+https://github.com/danielhomola/mifs
    - pymrmr
    - featuretools
    - featureforge
    - few # feature engineering wrapper
    - feagen==1.0.0a9
    - git+https://github.com/mewwts/feng.git
    - features
    - sklearn_features
    - sklearn_relief
    - sklearn-pandas
    - ibex # pandas + sklearn interface
    - csvdedupe
    - delorean
    - prince
    - ppca
    - sklearn_dummies
    - sklearn-deltatfidf
    - fbpca
    - tzlocal
    - lcfeatures
    - mercantile
    - git+https://github.com/caseyclements/pennies #finance modeling abt pricing
    - empyrical

# a/b testing / exploration thru bandits and similar ideas
    - git+https://github.com/mpkato/interleaving.git
    - hastur
    - parfit
    - striatum
    - git+https://github.com/Nth-iteration-labs/streamingbandit
    - git+https://github.com/cbellei/abyes.git
#    - babtest uses pymc + python2


# databases
    - db.py
    - dataset # Easy-to-use data handling for SQL data stores with support for implicit table creation, bulk loading, and transactions.


# Testing
    - datatest   # validation tools for test-driven data wrangling
    - tdda
    - mltest
    - pytest-mpl

# Network Analysis
    - git+https://github.com/austin-taylor/flare.git         # network traffic and behavioral analytics
#    - git+https://github.com/rafguns/linkpred.git       # link prediction tool should update the networkx version
    - git+https://github.com/dmarx/Topological-Anomaly-Detection
    - networkl # networkx extension
    - graphistry
    - networkit
    - python-louvain     # Louvain Community Detection (network analysis)

# Time Series
    - git+https://github.com/ceholden/yatsm.git #gdal library required
    - seasonal     # Robustly estimate trend and periodicity in a timeseries.
    - pyflux
    - tslearn     # time-series data ml
    - cesium     # Machine Learning Time-Series Platform
    - pydlm
    - changepy
    - pastas
    - pyts
    - dtaidistance
    - git+git://github.com/kyleclo/structural.git#egg=structural

# External Data
    - workalendar    # Worldwide holidays and workdays computational toolkit
    # - pandas-finance
    - iso3166
    # - yahoo-finance
    - pycountry

# pretrained models
    - gender-guesser
    - langid
    - probablepeople>=0.5.2
    - nudepy
    - sexmachine
    - ethnicolr
    - usaddress
    - street-address

# OR Packages
    - ortools
    - vania
    - cvxpy
    - simanneal

# image processing
    - imgaug

# algorithms
    - git+https://github.com/kalaidin/sketches
    - git+https://github.com/mattilyra/LSH.git
    - git+https://github.com/erp12/pyshgp.git # soon from pip
    - git+https://github.com/aarongarrett/inspyred
    - squarify
    - trueskill
    - git+https://github.com/wdm0006/elote
    - pymining
    - pygorithm
  # - git+https://github.com/clips/pattern@development # this has a server for some reason

# Support Packages
    - futures>=3.0.5
    - progress
    - humanize
    - prettytable
    - pyperclip

#automl
#    - git+https://github.com/tadejs/autokit.git
#    - auto_ml
#    - alphapy
#    - mlbox
#    - auto-sklearn


# model interpretation and management and meta-learning
    - git+https://github.com/MaxHalford/xam
    - hpsklearn
    - git+https://github.com/mpearmain/scikit-wrapRs.git
    - git+https://github.com/automl/RoBO.git #needs swig george and emcee
    - git+https://github.com/mpearmain/gestalt
    - git+https://github.com/kootenpv/xtoy.git
    - git+https://github.com/dvaida/hallucinate.git
    - git+https://github.com/automl/fanova.git
    - pdpbox # python partial dependence plot toolbox
    - civisml-extensions
    - visualize_ML     #  visualize some processes involved in Machine learning.
    - tensorboardX
    - mlens     #  ensemble learning
    - xgbfir     # XGBoost Feature Interactions
    - tensorboard_logger
    - lens
    - speedml # speed start machine learning projects
    - git+https://github.com/lmc2179/savvy
    - scikits.bootstrap
    - hyperopt
    - searchgrid
    # - smac # needs pyrfr
    - omesa
    - boruta
    - dflearn
    - ml_insights
    - shap
    - pdpipe
  # - quilt
  # - persimmon needs client graphics
    - heamy
    - vecstack # models stacking
    - stacking
    - pypet # exploration of the parameter space
    - sklearn-gbmi
    - sigopt_sklearn[ensemble]
    - artemis-ml
    - sklearn_pipeline_utils
    - sklearn-evaluation
    - optml
    - pycebox
    - boostaroota
    - kmeans-smote
    - treeinterpreter
    - skrebate
    - lore
    - git+https://github.com/yandexdataschool/modelgym
    - mlcrate
    - rf_perm_feat_import
    - anchor_exp
    - git+https://github.com/szagoruyko/pytorchviz #  visualizations of PyTorch execution graphs and traces.
    - git+https://github.com/paris-saclay-cds/ramp-workflow.git


# model deployment
    - sklearn2pmml

# NLP
    - keras-text
    - ktext
    - skift
    - pykoko
    - wordsegment
    - pyahocorasick
    - emoji
    - spacy-lookup
    - flashtext
    - wordbatch     # Parallel text feature extraction for machine learning
    - babel
    - pyparsing #  construct the grammar directly in Python code
    - textacy   # built on spacy
    - textblob
#    - fasttext     #  interface for Facebook fastText
#    - pyfasttext
    - thinc
    - sematch     # semantic similarity framework for knowledge graph
    - snowballstemmer
    - fuzzywuzzy     # Fuzzy String Matching
    - pynlpl
    - stop-words
    - sentencepiece
    - bounter
    - pronouncing
    - python-louvain
    - stemming
    - leven
    - janome # Add Japanese morphological analysis engine
    - jellyfish
    - jieba
    - lda
    - git+https://github.com/ztane/python-Levenshtein.git
    - allennlp
    - preprocessing
    - chakin
    - git+https://github.com/faneshion/MatchZoo.git # text matching


# deep learning
    - mxnet     # dl framework
    - https://cntk.ai/PythonWheel/CPU-Only/cntk-2.4-cp36-cp36m-linux_x86_64.whl     # dl toolkit
    - nnabla
    - dm-sonnet     # TensorFlow-based neural network library from deepmind
    - nervananeon
    - skorch
    - tflearn
    - tensorlayer
    - tensorflow-lattice
    - keras-vis
    - gulpio     # Binary storage format for large volume dl data.
    - pyro-ppl # deep probabilistic programming
    - luminoth # DL toolkit for Computer Vision
    - keras-rl     # Deep Reinforcement Learning
    - hyperas
    - git+https://github.com/broadinstitute/keras-rcnn
    - neupy
    - tensorly
    - git+git://github.com/probtorch/probtorch
    - fastai
    - quiver_engine     # Interactive convnet features visualization for Keras
    - foolbox
    - t3f
