name: root
channels:
  - conda-forge
  - glemaitre
  - maciejkula
  - ioam
  - defaults
  - pkgw-forge
  - datamicroscopes
  - distributions

dependencies:
  - python=3.6
  - jupyterlab
  - tim_shawver/label/dev::qgrid==1.0.0b10
  - ipywidgets
  - boost
  - paramnb
  - beakerx
  - nodejs
  - openjdk
  - maven
  - libgcc
  - gdal>=2.1 # required by yatsm

  # Cloud Services
  - boto
  - boto3
  - google-cloud-core
  - s3fs

  # python toolings
  - cytoolz
  - toolz
  - pytools
  - python-dotenv
  - fire
  - tqdm

  # formatting
  - mccabe
  - flake8
  - yapf

  # Stats and math
  - sympy
  - scipy>=0.19.*
  - patsy>=0.4.*
  - statsmodels>=0.6.*
  - haversine
  - emcee
  #- kcbo # ver old... someone should update it
  # - sixpack # ab testing

  # profiling code
  - line_profiler
  - memory_profiler


  # Data Exploration
  - jos_pol::pandas-profiling
  - missingno     # Missing data visualization module



  # Data Analysis Tools
  - pandas>=0.22.0
  - fastparquet
  - cloudpickle>=0.2.*
  - dask>=0.15.*
  - dask-ml
  - dask-xgboost
  - distributed
  - h5py>=2.7.*
  - hdf5>=1.8.*
  - numba
  - numexpr>=2.6.*
  - numpy
  - bcolz
  - hyperspy  # multi-dimensional data analysis
  - arrow
  - xarray
  - scikit-sparse # sparse data lib



  # Visualization
  - bokeh>=0.12.*
  - matplotlib>=2.*
  - ggplot
  - plotly
  - matplotlib-venn     # Area-weighted venn-diagrams for Python/matplotlib
  - plotnine # grammar of graphics
  - seaborn # statistical data visualization
  - bokeh::datashader   # visualize big datasets
  - conda-forge::altair
  - mpld3   # D3 Renderings of Matplotlib Graphics
  - ioam::holoviews
  - districtdatalabs::yellowbrick     # Visual analysis and diagnostic tools to facilitate machine learning model selection

  - bokeh::colorcet # colormaps
  - mplleaflet
  #- glueviz::glueviz
  - folium
  - mpl-scatter-density
  - bqplot
  - descartes # visualize geopositions
  - amueller::wordcloud
  - ipyleaflet
  - windrose


  # General Purpose ML
  - orange3
  - python-annoy   # Approximate Nearest Neighbors
  - scikit-learn>=0.18.1
  - glemaitre::imbalanced-learn
  - hdbscan
  - h2oai::h2o
  - xgboost
  - sklearn-contrib-lightning   # Large-scale linear classification, regression and ranking i
  - nearpy     # approximated nearest neighbour
  - lightgbm
  - lmfit


  # specific problem ml libs
  - lifelines # Survival analysis
  - spotlight
  - george
# - face_recognition
  #- nupic


  # databases read
  - records

  # Bayesian
  - conda-forge::pymc3
  - pomegranate #probabilistic modelling
  - pystan


  # preprocessing & feature engineering
  - category_encoders
  - csvkit
  - ftfy
# - sklearn-deap2
# - sklearn-deap

# geo spatial data
  #- fiona
  #- pyshp
  #- rpforest # random projections forest
    # - geopandas
 # - geoplotlib
  # - geoplot   # geospatial data visualization
#   - shapely>=1.5.*
#   - cartopy>=0.14.2
#   - basemap
#  - geoviews
#   - gmaps
  # - gpxpy   # gps format parser
  # - geojson
  # - pysal # spatial data analysis

  # Testing
  - pytest
  - cerberus     # data validation functionality
  - validictory
  - engarde
  - hypothesis


  # Network Analysis
  - networkx>=2.*
  - graphviz
  - python-igraph
  - nxviz
  - ostrokach-forge::graph-tool


# Time Series
  - tsfresh   # Automatic extraction of relevant features from time series
  - fbprophet


# Models Interpretation and management and meta learning
  - Skater # Model Agnostic Interpretation
  - eli5 # inspecting machine learning classifiers and explaining their predictions
  - scikit-plot     # add plotting functionality to scikit-learn objects.
  - mlxtend  # extension and helper modules for Python's data analysis and machine learning libraries.
  - lime
  - pandas_ml     # pandas, scikit-learn, xgboost and seaborn integration
  - scikit-optimize
  # rep --no-dependencies
    # - modeldb
  # - sacred
  # - skll # easy to run machine learning experiments (scikit-learn)
    # - xcessiv

  # External Data
  - geopy


  # workflow managements & parallelization
#  - airflow
  - luigi
#  - horovod
  - joblib
  - dask-searchcv

# algorithms
  - uwmagellan::py_stringsimjoin


  # OR packages
  - pyomo
  - pyomo.extras
  - salib
  - cvxopt
  - pulp


  # suport others
  #- lesscpy # may be needed by some tool
  - cython
  #- swig
  - mistune
  - tabulate
  - requests>=2.*
  - paramz
  - lxml>=3.6.0
  - pyyaml
  - funcy
  - cmd2
  - bottleneck # faster pandas
  - rpy2 # interface to R from python
  # - knowledge-repo #(should be in a dockerfile by itself)

# NLP
  - nltk
  - gensim
  - spacy
#  - flashtext
#  - wordbatch     # Parallel text feature extraction for machine learning
# Natural Language Processing
#   - orange3-text
#   - snowballstemmer
#   - babel
#   - pyparsing #  construct the grammar directly in Python code.  (nlp)
#   - textacy   # nlp built on spacy
#     - textblob
#     - fasttext     #  interface for Facebook fastText
#     - pyfasttext
#     - thinc
#     - sematch     # semantic similarity framework for knowledge graph
#   - snowballstemmer
#   - babel
#     - fuzzywuzzy     # Fuzzy String Matching
#     - pynlpl
#     - stop-words
# - chatterbot
# - git+https://github.com/ztane/python-Levenshtein.git
# - affinegap
# - git+https://github.com/jamesturk/jellyfish.git
# - jieba
# -
# - lda
# -pronouncing
#   python-louvain && \
#   stemming && \
#    leven && \
# sentencepiece
# - bounter
# -


# Image Processing
#   - SimpleITK::SimpleITK
#   - imagesize>=0.7.1 parses image files’ header and return image size.
#   - ImageHash   # image hashing library
#   - scikit-image>=0.12.*
#   - opencv
#   - Pillow
#   - pdftabextract
#   - imagesize>=0.7.1
#   - tifffile
#   - imgaug
# - vtk

# Neuroscience & Medical & molecular Biology
#   - dipy
#   - nibabel #neuroimaging file format
#   - pydicom # read/ write dicom files
#  - nilearn
# - biopython
  # - mne # human neurophysiological data
#  - git+https://github.com/analysiscenter/cardio.git ml for cardio data

# Astronomy
#   - PyAstronomy
#   - astroML

# Audio
#   - librosa
# - python_speech_features

# Geometry
#   - s2sphere

  - r::r-essentials
  - r::r-devtools
  - r::r-base
  - r::r-irkernel
  - r::r-plyr
  - r::r-shiny
  - r::r-tidyverse
  - r::r-markdown
  - r::r-forecast
  - r::r-reshape2
  - r::r-randomforest
  - r::r::r-caret
  - r::r-ggplot2
  - rpy2
  - r::r-rsqlite
  - r::r-caret
  - r::r-rcurl
  - r::r-tseries
  - r::r-survival
  - r::r-rstan
  - r::r-rocr
  - r::r-lme4
  - r::r-kernsmooth
  - r::r-glmnet
  - r::r-ggplot2
  - r::r-modelmetrics
  - r::r-e1071
  - r::r-anomalydetection
  - r::r-rcpp
  - r::r-crayon

  - pip:
# python-toolings
    - disp
    - kaggle-cli
    - mmh3

# command_lines
    - s3cmd

# data processing

# stats and math
    - bootstrapped
    - fitter
    - ml_metrics
    - bayesian_bootstrap
    - bayesian-optimization
    - causalinference
#    - causality needs pymc ... should be switched to pymc3
    - cma
    - pgmpy
    - elfi
    - expan
    - pymc3_models

# data exploration
    - optimuspyspark     # cleaning and much more, pre-processing and exploratory data analysis in a distributed fashion with Apache Spark

# data analysis tools
    - meza     # processing tabular data
    - datacleaner     #  automatically cleans data sets and readies them for analysis.
    - Geohash
    - prices
    - tdigest # data structure for large data analysis
    - urlextract
    - messytables
    - barely_json
    - rows #tabular data with wierd formats
    - pyexcel-ods    # ods formats
    - pythonflow


# profiling & debugging code
    - py-heat
    - pudb



# visualizations
    - kmapper
    - umap-learn
    - hypertools
    - matplotlib_venn_wordcloud
    - pyldavis
    - jmpy
    - cufflinks
    - pyhsmm
    - bhtsne # is it better than scikit-learn ... should be tested

# general ML
    - scikit-garden  # A garden for scikit-learn compatible trees
    - scikit-multilearn
    - git+https://github.com/larsmans/seqlearn.git     # Sequence learning toolkit
    - git+git://github.com/scikit-learn-contrib/forest-confidence-interval.git #forestci
    - git+https://github.com/arogozhnikov/infiniteboost.git     # building infinite ensembles with gradient descent
    - git+https://github.com/skope-rules/skope-rules.git
    - git+https://github.com/scikit-learn-contrib/py-earth.git
    - pystruct # structured learning
    - kmodes     # k-modes and k-prototypes clustering algorithms
#    - vowpalwabbit # could not find boost library
    - catboost
    - sklearn-compiledtrees
    - lightfm
    - guidedlda
    - minisom
    - hdidx
    - linearmodels
    - rgf_python # just an interface ... should install the tool too
    - fastFM
    - sklearn-glvq
    - markovify
    - xlearn
    - glmnet_py
    - git+https://github.com/stitchfix/diamond
    # - sklearn-extensions old version supporting only old libs

# Specific ML
    - lifetimes # Lifetime value
    - git+https://github.com/nicolashennetier/pyeconometrics.git # econometrics regression models
  #  - git+https://github.com/tmadl/semisup-learn it installs wrong sklearn
    - git+https://github.com/timvieira/crf.git
    - pystruct
    - sklearn-crfsuite
    - parserator>=0.6.2
    - dedupe
    - dedupe-hcluster
    - gplearn
    - metric-learn
    - git+https://github.com/garydoranjr/misvm.git#egg=misvm
    - flurs
    - implicit
    - hep_ml
    - pygam # Generalized Additive Models in Python
    - git+https://github.com/albertcthomas/anomaly_tuning
    - libact # active learning needs liblapacke-dev
    - scikit-survival
    - git+https://github.com/jamalsenouci/causalimpact.git
#    - causal-impact


# Bayesian
    - bambi     # BAyesian Model-Building Interface
    - git+https://github.com/AmazaspShumik/sklearn_bayes.git
    - git+https://github.com/scikit-learn-contrib/polylearn.git
    - git+https://github.com/marinkaz/scikit-fusion.git
#    - git+https://github.com/nicta/dora.git # Nonparametric Active Sampling
    - edward
    - hmmlearn # Hidden Markov Models
    - MarkovNetwork
    - scikit-surprise
    - lsanomaly # probabilistic anomaly detector
    - bayespy

# Preprocessing and feature engineering
    - fancyimpute     # impute missing data
    - git+https://github.com/EESI/PyFeast.git # Feature Selection Toolkit, contains JMI, BetaGamma, CMIM, CondMI, DISR, ICAP, and mRMR
    - git+https://github.com/jundongl/scikit-feature
    - featuretools
    - featureforge
    - few # feature engineering wrapper
    - git+https://github.com/ianlini/feagen.git
    - git+https://github.com/mewwts/feng.git
    - features
    - sklearn_features
    - sklearn_relief
    - sklearn-pandas
    - ibex # pandas + sklearn interface
    - csvdedupe
    - delorean
    - prince
    - ppca
    - sklearn_dummies
    - sklearn-deltatfidf
    - fbpca
    - tzlocal
    - lcfeatures

    - git+https://github.com/caseyclements/pennies #finance modeling abt pricing

# a/b testing and similar ideas
    - git+https://github.com/mpkato/interleaving.git
    - hastur
    - parfit
#    - babtest uses pymc + python2


# databases
    - db.py
    - dataset # Easy-to-use data handling for SQL data stores with support for implicit table creation, bulk loading, and transactions.


# Testing
    - datatest   # validation tools for test-driven data wrangling
    - tdda

# Network Analysis
    - git+https://github.com/austin-taylor/flare.git         # network traffic and behavioral analytics
    - git+https://github.com/rafguns/linkpred.git       # link prediction tool
    - git+https://github.com/dmarx/Topological-Anomaly-Detection
    - networkl # networkx extension
    - graphistry
    - networkit
    - python-louvain     # Louvain Community Detection (network analysis)

# Time Series
    - git+https://github.com/ceholden/yatsm.git #gdal library required
    - seasonal     # Robustly estimate trend and periodicity in a timeseries.
    - pyflux
    - tslearn     # time-series data ml
    - cesium     # Machine Learning Time-Series Platform

# External Data
    - workalendar    # Worldwide holidays and workdays computational toolkit
    # - pandas-finance
    - iso3166
    # - yahoo-finance
    - pycountry

# pretrained models
    # - gender-guesser
    # - langid
    # - probablepeople>=0.5.2
    # - nudepy
    # - sexmachine
    # - ethnicolr
    # - usaddress
    # - street-address

# OR Packages
    - ortools
    - vania
    - cvxpy
    - simanneal


# algorithms
    - git+https://github.com/kalaidin/sketches
    - git+https://github.com/mattilyra/LSH.git
    - git+https://github.com/erp12/pyshgp.git
    - git+https://github.com/aarongarrett/inspyred
    - squarify
    - trueskill
    - git+https://github.com/wdm0006/elote
    - pymining
  # - git+https://github.com/clips/pattern@development

# Support Packages
    - futures>=3.0.5
    - progress
    - humanize
    - prettytable
    - pyperclip

#automl
#    - git+https://github.com/tadejs/autokit.git
#    - tpot # old in conda
#    - auto_ml
#    - alphapy
#    - mlbox


# model interpretation and management and meta-learning
    - git+https://github.com/MaxHalford/xam
    - git+https://github.com/hyperopt/hyperopt-sklearn.git
    - git+https://github.com/mpearmain/scikit-wrapRs.git
    - git+https://github.com/automl/RoBO.git #needs swig george and emcee
    - git+https://github.com/mpearmain/gestalt
    - git+https://github.com/kootenpv/xtoy.git
    - git+https://github.com/dvaida/hallucinate.git
    - git+https://github.com/automl/fanova.git
    - git+https://github.com/SauceCat/PDPbox.git
    - civisml-extensions
    - visualize_ML     #  visualize some processes involved in Machine learning.
    - tensorboardX
    - mlens     #  ensemble learning
    - xgbfir     # XGBoost Feature Interactions
    - tensorboard_logger
    - lens
    - speedml # speed start machine learning projects
    - git+https://github.com/lmc2179/savvy
    - scikits.bootstrap
    - hyperopt
    - searchgrid
    # - smac # needs pyrfr
    - omesa
    - boruta
    - dflearn
    - ml_insights
    - pdpipe
  # - quilt # - persimmon needs client graphics
    - heamy
    - vecstack # models stacking
    - pypet # exploration of the parameter space
  # - https://github.com/automl/auto-sklearn
    - sklearn-gbmi
    - sigopt_sklearn[ensemble]
    - artemis-ml
    - sklearn_pipeline_utils
    - sklearn-evaluation
    - optml
    - pycebox
    - boostaroota
    - kmeans-smote

# model deployment
    - git+https://github.com/jpmml/sklearn2pmml.git
